apiVersion: v2
name: discord-backup-bot
description: A Helm chart for the discord backup bot
type: application

version: 0.3.0

# App metadata
appVersion: "v0.10.0"
sources:
  - https://github.com/EthDevOps/EFDiscordBackupBot
maintainers:
  - name: elasticroentgen
    email: markus.keil@ethereum.org
