secretName: my-secret
secretKey: GITHUB_TOKEN

# Tenant identifier
tenant: ""
# Project identifier
project: ""
imageVersion: v0.1.0

# semaphore config
semaphoreUrl: ""
semaphoreToken: ""

clusterName: ""
mattermostWebhook: ""
