{{- if and .Values.app.persistence.enabled (not .Values.app.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "domainmod.fullname" . }}-app
  labels:
    {{- include "domainmod.labels" . | nindent 4 }}
  {{- with .Values.app.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.app.persistence.accessModes | nindent 4 }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size | quote }}
{{- end }}
