{{- if not .Values.dbCredentials.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "domainmod.fullname" . }}
  labels:
    {{- include "domainmod.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.dbCredentials.password | b64enc | quote }}
  root-password: {{ .Values.dbCredentials.rootPassword | b64enc | quote }}
{{- end }}
