{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "domainmod.db.fullname" . }}
  labels:
    {{- include "domainmod.db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "domainmod.db.selectorLabels" . | nindent 4 }}
{{- end }}
