imageTag: v0.2.0
imageName: docker.ethquokkaops.io/ethquokkaops/ethdevops/github-actions-autoscaler
hostname: autoscaler.example.com
resources: {}
ingressClassName: haproxy
envFromSecret: ""
postgresql:
  enabled: true
  image:
    tag: 13-alpine
  auth:
    username: runners
    database: runners
    password: runners
    postgresPassword: runners
ingress:
  enabled: true
observability:
  otelExporterEndpoint: ""
  otelAuth:
    user: ""
    password: ""
    existingSecret: ""
    userKey: "user"
    passwordKey: "password"
  pyroscopeServerAddress: ""
  pyroscopeAuth:
    user: ""
    password: ""
    existingSecret: ""
    userKey: "user"
    passwordKey: "password"
service:
  type: ClusterIP
  annotations: {}
